# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='is_company',
            field=models.BooleanField(default=False, verbose_name='company'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_lawyer',
            field=models.BooleanField(default=False, verbose_name='lawyer'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Emerson', max_length=100, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
